#include <windows.h>

#define IDM_MAINMENU			100
#define ID_ITEM_FILE_OPEN		10101
#define IDC_MULTIVIEW			201
#define IDC_MULTIVIEWITEMSPANEL	202
#define IDC_MULTIVIEWITEM		203
#define ID_MULTIVIEWITEM_START	(WM_APP + 100)
