#include <windows.h>

#define IDM_MAINMENU				100
#define ID_ITEM_FILE_OPEN			10101
#define IDC_MULTIVIEW				201
#define IDC_MULTIVIEWITEMSPANEL		202
#define ID_MULTIVIEWITEM_START		300
#define ID_CTRL_START				1000
